// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfig
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BuildingType : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BuildingType GetRootAsBuildingType(ByteBuffer _bb) { return GetRootAsBuildingType(_bb, new BuildingType()); }
  public static BuildingType GetRootAsBuildingType(ByteBuffer _bb, BuildingType obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BuildingType __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public int BaseHealth { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)100; } }
  public int MaxCapacity { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1000; } }
  public int MinCapacity { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)100; } }
  public GameConfig.TypeOfCapability TypeOfCapability { get { int o = __p.__offset(12); return o != 0 ? (GameConfig.TypeOfCapability)__p.bb.GetSbyte(o + __p.bb_pos) : GameConfig.TypeOfCapability.TypeSoldier; } }

  public static Offset<GameConfig.BuildingType> CreateBuildingType(FlatBufferBuilder builder,
      short id = 0,
      int base_health = 100,
      int max_capacity = 1000,
      int min_capacity = 100,
      GameConfig.TypeOfCapability type_of_capability = GameConfig.TypeOfCapability.TypeSoldier) {
    builder.StartTable(5);
    BuildingType.AddMinCapacity(builder, min_capacity);
    BuildingType.AddMaxCapacity(builder, max_capacity);
    BuildingType.AddBaseHealth(builder, base_health);
    BuildingType.AddId(builder, id);
    BuildingType.AddTypeOfCapability(builder, type_of_capability);
    return BuildingType.EndBuildingType(builder);
  }

  public static void StartBuildingType(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, short id) { builder.AddShort(0, id, 0); }
  public static void AddBaseHealth(FlatBufferBuilder builder, int baseHealth) { builder.AddInt(1, baseHealth, 100); }
  public static void AddMaxCapacity(FlatBufferBuilder builder, int maxCapacity) { builder.AddInt(2, maxCapacity, 1000); }
  public static void AddMinCapacity(FlatBufferBuilder builder, int minCapacity) { builder.AddInt(3, minCapacity, 100); }
  public static void AddTypeOfCapability(FlatBufferBuilder builder, GameConfig.TypeOfCapability typeOfCapability) { builder.AddSbyte(4, (sbyte)typeOfCapability, 0); }
  public static Offset<GameConfig.BuildingType> EndBuildingType(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfig.BuildingType>(o);
  }
}


static public class BuildingTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 6 /*BaseHealth*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*MaxCapacity*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*MinCapacity*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*TypeOfCapability*/, 1 /*GameConfig.TypeOfCapability*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
