// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfig
{

public enum TypeOfCapability : sbyte
{
  TypeSoldier = 0,
  TypeShooter = 1,
};


}
